services:
  postgres:
    image: postgres:13.16-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  manager:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./manager
    container_name: manager
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

  discord-bot:
    depends_on:
      - manager
      - redis
    build: .
    container_name: boo
    command: sh -c "python src/main.py"
    restart: always
    environment:
      - ADMIN_LIST=${ADMIN_LIST}
      - CONTEXT_LIMIT=${CONTEXT_LIMIT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TENOR_API_KEY=${TENOR_API_KEY}
      - DB_SERVICE_BASE_URL=manager:8080
      - TOMORROW_IO_API_KEY=${TOMORROW_IO_API_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CF_WORKERS_MODEL_NAME=${CF_WORKERS_MODEL_NAME}
      - CF_WORKERS_IMAGE_MODEL_NAME=${CF_WORKERS_IMAGE_MODEL_NAME}
      - CLOUDFLARE_WORKERS_AI_API_KEY=${CLOUDFLARE_WORKERS_AI_API_KEY}
      - CF_WORKERS_IMAGE_DESCRIPTION_MODEL_NAME=${CF_WORKERS_IMAGE_DESCRIPTION_MODEL_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres_data:
  redis_data:
